ingress:
  enabled: true
  annotations: {}
#    certmanager.k8s.io/cluster-issuer: letsencrypt-production
  path: /
  hosts:
  - staging-all-bases.grannec.com
  tls: []
#    - secretName: josmo-staging-all-tls
#      hosts:
#        - staging-all-bases.grannec.com